module.exports = function(sequelize, DataTypes) {
    var driver = sequelize.define("driver", {
      // The email cannot be null, and must be a proper email before creation
        driverId:{
            type: DataTypes.INTEGER,
            allowNull:false,
            autoIncrement:true,
            unique:true,
            primaryKey:true
        },
        licenceNumber:{
            type: DataTypes.STRING,
            allowNull:true
        },
        /* memId:{
            //FK to members
            type: DataTypes.INTEGER,
            allowNull:false,
        }, */
        defaultVehicle:{
            //FK to vehicles
            type: DataTypes.STRING, // simplified database FKs are autogenerated by sequelize
            allowNull:true,
        },
        homeAddress:{
            //ref to ausstates
            type: DataTypes.STRING, // simplify database
            defaultValue: "Perth, WA",  //defaults to Perth, WA
            allowNull:true,
        },
        expiryDate: {
            allowNull: true,
            type: DataTypes.DATEONLY
        },
        freeSpots:{ // simplified database
            type: DataTypes.INTEGER,
            allowNull:true,
        },
        workingWithChildren:{
            //Does the driver have an official working with children check?
            type: DataTypes.BOOLEAN,
            allowNull:true,
            defaultValue:false
        },
        defaultRoute:{
            //FK to routes
            type: DataTypes.STRING, // simplified database changed to string
            allowNull:true,
        },
        createdAt: {
            allowNull: false,
            type: 'TIMESTAMP',
            defaultValue: sequelize.literal('CURRENT_TIMESTAMP')
        },
        updatedAt: {
            allowNull: false,
            type: 'TIMESTAMP',
            defaultValue: sequelize.literal('CURRENT_TIMESTAMP')
        }



    });

    driver.associate = function(models) {
        // Associating Drive with member, vehicles, routes
    
        driver.belongsTo(models.member);
        driver.hasMany(models.vehicle, {
            onDelete: "cascade"
          });
        driver.hasMany(models.route, {
            onDelete: "cascade"
          });
          
      };
    


    return driver;
  };
